# Generated by Django 2.2.7 on 2019-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(default=None)),
                ('Y', models.FloatField(default=None)),
                ('Unique_Squirrel_ID', models.CharField(max_length=20)),
                ('Hectare', models.CharField(max_length=3)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.DateField(help_text='Date of the sighting happened')),
                ('Hectare_Squirrel_Number', models.IntegerField(blank=True, null=True)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenlie'), ('?', '?'), ('Null', '')], default='Null', max_length=20)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Null', '')], default='Null', max_length=20)),
                ('Highlight_Fur_Color', models.CharField(max_length=50)),
                ('Color_Notes', models.CharField(max_length=500)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('Null', '')], default='Null', max_length=20)),
                ('Above_Ground_Sighter_Measurement', models.IntegerField(blank=True, null=True)),
                ('Specific_Location', models.CharField(max_length=500)),
                ('Running', models.BooleanField(default=False)),
                ('Chasing', models.BooleanField(default=False)),
                ('Climbing', models.BooleanField(default=False)),
                ('Eating', models.BooleanField(default=False)),
                ('Foraging', models.BooleanField(default=False)),
                ('Other_Activities', models.CharField(max_length=500)),
                ('Kuks', models.BooleanField(default=False)),
                ('Quaas', models.BooleanField(default=False)),
                ('Moans', models.BooleanField(default=False)),
                ('Tail_Flags', models.BooleanField(default=False)),
                ('Tail_Twitches', models.BooleanField(default=False)),
                ('Approaches', models.BooleanField(default=False)),
                ('Indifferent', models.BooleanField(default=False)),
                ('Runs_From', models.BooleanField(default=False)),
                ('Other_Interactions', models.CharField(max_length=500)),
            ],
        ),
    ]
