# Generated by Django 2.2.7 on 2019-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191203_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='Combination',
            field=models.CharField(default='Null', max_length=70),
        ),
    ]
